context:
  name: zed
  version: "0.220.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/zed-industries/zed/archive/v${{ version }}.tar.gz
    sha256: 553f2356fcb81ef01031a6ea3fe522748369f4d475c6bb06e0d9c87b795a0035

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - pkg-config
    - cmake

  host:
    - if: linux
      then:
        - alsa-lib
        - curl
        - libxcb
        - openssl
        - sqlite
        - libvulkan-loader
        - vulkan-tools
        - wayland
        - zlib
        - zstd
        - clang
        - mold
        - cmake
        - xorg-libx11
        - xorg-xproto
        - xorg-kbproto
        - libxkbcommon

tests:
  - script:
      - zed --help
about:
  homepage: https://zed.dev/
  summary: Code at the speed of thought
  description: |
    Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter.
  license: Apache-2.0
  license_file:
    - LICENSE-AGPL
    - LICENSE-APACHE
    - LICENSE-GPL
    - THIRDPARTY.yml
  repository: https://github.com/zed-industries/zed

extra:
  recipe-maintainers:
    - lucascolley
    - Hofer-Julian
