conda_build_tool: rattler-build
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
azure:
  settings_osx:
    pool:
      vmImage: macos-13
  store_build_artifacts: true
  # free up some extra space on the default Azure Pipelines
  # linux image before running the Docker container for building
  free_disk_space: true
test: native_and_emulated
bot:
  automerge: true
