conda_build_tool: rattler-build
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
azure:
  settings_osx:
    pool:
      vmImage: macos-13
  store_build_artifacts: true
test: native_and_emulated
